### ISSUE TITLE
你好，使用你的efi出现下列两个问题

### ISSUE THREAD

**Issue by yhf2lj** [irelandKen/MSI-B360M-MORTAR-TITANIUM-EFI#1]
1. 在开机进入clover的时候，没有usb引导的符号了
2. 我添加了hfsplus.efi和另一个osxaptiofoxdrv-64后可以进入啰嗦模式，但是卡在了一个“ptidsensor：started”的一行，尚未搜索到解决办法

主板：B360 mortar
cpu：i7-8700
显卡：UHD630

**Comment by irelandKen** [comment]
后来问题解决了没？

**Comment by yhf2lj** [comment]
解决了，第一个问题我添加了osxaptiofoxdrv-64后可以usb进入

第二个问题，是我更新了bios到最新版，所以一直过不去，后来回退了一个版本就立刻成功了

后来我用了sleele的efi文件

**Comment by irelandKen** [comment]
GOOD
