### ISSUE TITLE
使用该EFI之后出现关机变成重启的情况

### ISSUE THREAD

**Issue by zhuzhuani** [irelandKen/MSI-B360M-MORTAR-TITANIUM-EFI#5]
请问应该如何解决鸭。。。。

**Comment by irelandKen** [comment]
刚开始貌似我也遇到这个问题, 后面好像又没有了.. 不过我的设备用来写代码, 经常两星期以上不关机...
后面再确认一下...

**Comment by zhuzhuani** [comment]
好的 感谢

**Comment by irelandKen** [comment]
@zhuzhuani 已修复; 请升级到最新的master版本

应该是加入了EmuVariableUefi-64.efi解决的; 

这个驱动修复了NVRAM的写入问题吧; 

睡眠需要写NVRAM保存状态
